# default config.yaml
action: run
verbose: false

# Overrides / options
geojson: null
start: null
end: null
output: null
output_dir: ./out
output_uri: ${output_dir}
workers: 1
cells_per_task: 50
search_results: null
tasks: null
plugin_name: null
format: table

# ExtractionJob config defaults
search: null
pipeline: []
grid_config:
  _target_: aereo.interfaces.GridConfig
  target_grid_dist: 50000
patch_config:
  _target_: aereo.interfaces.PatchConfig
  resolution: 10.0
  padding: 0
  margin: 10.0
