defaults:
  - grid_dist@_global_: grid_10km
  - read@_global_: sentinel2
  - write@_global_: sentinel2
  - _self_

name: sentinel2_sample
target_aoi: config/aoi/chocon.geojson
output_uri: /tmp/aereo_extraction
overwrite: false
