defaults:
  - grid_config: grid_10km
  - patch_config: patch_10m
  - extract: tessera
  - _self_

name: tessera_sample
target_aoi: config/aoi/oxford.geojson
output_uri: /tmp/aereo_extraction
overwrite: false
