defaults:
  - search: sentinel2_pc
  - task_builder: grouped
  - grid_config: grid_10km
  - patch_config: patch_10m
  - extract: sentinel2
  - _self_

name: sentinel2_sample
target_aoi: config/aoi/chocon.geojson
output_uri: /tmp/aereo_extraction
overwrite: false
