defaults:
  - grid_dist@_global_: grid_10km
  - read@_global_: tessera
  - write@_global_: tessera
  - _self_

name: tessera_sample
target_aoi: config/aoi/oxford.geojson
output_uri: /tmp/aereo_extraction
overwrite: false
