read:
  _target_: aereo.builtins.ReadODCSTAC

preprocess:
  - _target_: aereo.builtins.NDVI
    ndvi_nir_band: B08
    ndvi_red_band: B04

reproject:
  _target_: aereo.builtins.ReprojectODC
  resampling: nearest


write:
  _target_: aereo.builtins.WriteGeoTIFF
