read:
  _target_: aereo.read_tessera.read_tessera
  _partial_: true
  bands: [0, 1, 2]

reproject:
  _target_: aereo.builtins.reproject.reproject_odc
  _partial_: true
  resampling: nearest
write:
  _target_: aereo.builtins.write.write_geotiff
