read:
  _target_: aereo.read_satpy.ReadSatpy
  reader: viirs_l1b
  wishlist: ["I04"]
reproject:
  _target_: aereo.reproject_satpy.ReprojectSatpy
  resampling: nearest
write:
  _target_: aereo.builtins.WriteGeoTIFF
