"""AEREO extract subcommands."""

from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer(help="Commands for remote AEREO extraction.")

_DOCKERFILE = """\
FROM ghcr.io/frandorr/aereo-extract-base:latest

# Install published pipeline plugins (uncomment as needed).
# RUN pip install --no-cache-dir \\
#     aereo-read-sentinel2 \\
#     aereo-reproject-epsg \\
#     aereo-write-cog

# Copy local custom package(s).
COPY ./{package} /opt/aereo/{package}
ENV PYTHONPATH=/opt/aereo

CMD ["aereo-extract-server"]
"""

_COMPOSE = """\
services:
  aereo-extract:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AEREO_LOG_LEVEL=info
    volumes:
      - ./output:/tmp/aereo/output
"""

_READER = """\
\"\"\"Custom reader generated by aereo-extract init-docker.\"\"\"

from __future__ import annotations

import numpy as np
import xarray as xr
from aereo.interfaces import ExtractionTask


class CustomReader:
    \"\"\"A minimal example reader.\"\"\"

    def __call__(self, task: ExtractionTask) -> xr.Dataset:
        shape = (64, 64)
        data = np.random.default_rng(42).random(shape)
        return xr.Dataset(
            {{"band": (["y", "x"], data)}},
            coords={{
                "y": np.linspace(0, 1, shape[0]),
                "x": np.linspace(0, 1, shape[1]),
            }},
        )
"""

_INIT = "from .custom_reader import CustomReader\n"

_INVOKE = """\
#!/usr/bin/env python3
\"\"\"Send a direct extraction task to the local container.\"\"\"

from __future__ import annotations

import base64
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import cast

import geopandas as gpd
import requests
from aereo.grid import ExtractionPatch
from aereo.interfaces import ExtractConfig, ExtractionTask, GridConfig, PatchConfig
from aereo.pipeline import ExtractionJob
from aereo.schemas import AssetSchema
from aereo.executors._serialization import _TaskSerializer
from {package}.custom_reader import CustomReader
from pandera.typing.geopandas import GeoDataFrame
from shapely.geometry import Polygon

URL = "http://localhost:8080/extract"
OUTPUT_PREFIX = "file:///tmp/aereo/output/job/0/"


def _make_task() -> ExtractionTask:
    from aereo.builtins.reproject import reproject_odc
    from aereo.builtins.write import write_geotiff

    df = gpd.GeoDataFrame(
        {{
            "id": ["asset_1"],
            "collection": ["custom"],
            "start_time": [datetime(2023, 1, 1)],
            "end_time": [datetime(2023, 1, 1)],
            "href": ["s3://bucket/key.tif"],
        }},
        geometry=[Polygon([[0, 0], [0.01, 0], [0.01, 0.01], [0, 0.01]])],
        crs="EPSG:4326",
    )
    patch = ExtractionPatch(
        id="0U_0R",
        d=50_000,
        cell_geometry=Polygon([[0, 0], [0.005, 0], [0.005, 0.005], [0, 0.005]]),
        resolution=100.0,
        margin=0.0,
        padding=0,
    )
    job = ExtractionJob(
        name="custom-job",
        grid_config=GridConfig(target_grid_dist=50_000),
        patch_config=PatchConfig(resolution=100.0),
        output_uri="/tmp/aereo/output",
        extract=ExtractConfig(
            read=CustomReader(),
            reproject=reproject_odc,
            write=write_geotiff,
        ),
    )
    return ExtractionTask(
        assets=cast(GeoDataFrame[AssetSchema], df),
        job=job,
        patches=[patch],
        task_context={{"job_id": "custom-job", "chunk_id": 0}},
    )


def main() -> int:
    task = _make_task()
    task_bytes = _TaskSerializer().serialize_to_bytes(task)
    payload = {{
        "mode": "direct",
        "task": base64.b64encode(task_bytes).decode("ascii"),
        "output_prefix": OUTPUT_PREFIX,
        "job_id": task.task_context["job_id"],
        "chunk_id": task.task_context["chunk_id"],
    }}
    resp = requests.post(URL, json=payload, timeout=60)
    print(json.dumps(resp.json(), indent=2))
    return 0 if resp.status_code == 200 else 1


if __name__ == "__main__":
    raise SystemExit(main())
"""

_README = """\
# {title} Remote Extract Project

Generated by `aereo-extract init-docker`.

## Local usage

```bash
docker compose up --build -d
pip install requests
python invoke_local.py
```

## AWS Lambda

Push the image to ECR and set the Lambda handler to:

```text
aereo_extract.handlers.handle_lambda
```
"""


@app.command(name="init-docker")
def init_docker(
    name: str = typer.Argument(..., help="Name of the project directory to create."),
    output: Path = typer.Option(
        Path("."), "--output", "-o", help="Directory where the project is created."
    ),
    package: str = typer.Option(
        "my_reader", "--package", "-p", help="Name of the custom reader package."
    ),
) -> None:
    """Scaffold a local Docker project for remote extraction."""
    project_dir = output / name
    if project_dir.exists():
        typer.echo(f"Directory already exists: {project_dir}", err=True)
        raise typer.Exit(code=1)

    package_dir = project_dir / package
    package_dir.mkdir(parents=True)
    (package_dir / "__init__.py").write_text(_INIT)
    (package_dir / "custom_reader.py").write_text(_READER)
    (project_dir / "Dockerfile").write_text(_DOCKERFILE.format(package=package))
    (project_dir / "docker-compose.yml").write_text(_COMPOSE)
    (project_dir / "invoke_local.py").write_text(_INVOKE.format(package=package))
    (project_dir / "README.md").write_text(
        _README.format(title=name.replace("-", " ").replace("_", " ").title())
    )
    (project_dir / "output").mkdir()

    typer.echo(f"Created remote extract project at {project_dir}")


if __name__ == "__main__":
    app()
