name: Integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: Install system dependencies for pyhdf
        run: sudo apt-get update && sudo apt-get install -y libhdf4-dev

      - name: Create venv
        run: uv venv

      - name: Install dependencies
        run: uv pip install pytest

      - name: Install aer-core
        run: uv pip install ./projects/aer-core

      - name: Run negative integration test (core only)
        run: uv run pytest test/integration/test_core_only.py

      - name: Install aer-search-earthaccess
        run: uv pip install aer-search-earthaccess

      - name: Run positive integration test (with plugin)
        run: uv run pytest test/integration/test_plugins.py
